// Bollinger Bands
//
// Original script: Tradingview built-in script
// Used as: C1 or C2 or Volume

bollinger_bands_length = input(20, minval=1)
bollinger_bands_src = input(close, title="Source")
bollinger_bands_mult = input(2.0, minval=0.001, maxval=50, title="StdDev")
basis = sma(bollinger_bands_src, bollinger_bands_length)
dev = bollinger_bands_mult * stdev(bollinger_bands_src, bollinger_bands_length)
upper = basis + dev
lower = basis - dev

//remove comments to use as C1 triggers
//Ind_1_Check_Trig = input(true, title = "Indicator 1 - C1 - Trigger")
//Ind_1_L_Trigger = Ind_1_Check_Trig ? crossover(close, upper) : false
//Ind_1_S_Trigger = Ind_1_Check_Trig ? crossunder(close, lower) : false

//remove comments to use as C2 confirmation
//Ind_2_Check_Conf = input(true, title = "Indicator 2 - C2 - Confirmation")
//Ind_2_L_Conf = Ind_2_Check_Conf ? close > upper : true
//Ind_2_S_Conf = Ind_2_Check_Conf ? close < lower : true