// Jurik Moving Average
//
// Original script: https://www.tradingview.com/script/nZuBWW9j-Jurik-Moving-Average/
// Used as: C1

jma_len = input(title="Length", defval=50)
jma_pha = input(title="Phase", defval=50)
jma_pow = input(title="Power", defval=2)

jurik(length, phase, power, src) =>
    phaseRatio = phase < -100 ? 0.5 : phase > 100 ? 2.5 : phase / 100 + 1.5
    beta = 0.45 * (length - 1) / (0.45 * (length - 1) + 2)
    alpha = pow(beta, power)
    jma = 0.0
    e0 = 0.0
    e0 := (1 - alpha) * src + alpha * nz(e0[1])
    e1 = 0.0
    e1 := (src - e0) * (1 - beta) + beta * nz(e1[1])
    e2 = 0.0
    e2 := (e0 + phaseRatio * e1 - nz(jma[1])) * pow(1 - alpha, 2) + pow(alpha, 2) * nz(e2[1])
    jma := e2 + nz(jma[1])
    jma

jma_ma = jurik(jma_len, jma_pha, jma_pow, close)

//remove comments to use as C1 triggers
//Ind_1_Check_Trig = input(true, title = "Indicator 1 - C1 - Trigger")
//Ind_1_L_Trigger = Ind_1_Check_Trig ? crossover(close, jma_ma) : false
//Ind_1_S_Trigger = Ind_1_Check_Trig ? crossunder(close, jma_ma) : false

//remove comments to use as C2 confirmation
//Ind_2_Check_Conf = input(true, title = "Indicator 2 - C2 - Confirmation")
//Ind_2_L_Conf = Ind_2_Check_Conf ? close > jma_ma : true
//Ind_2_S_Conf = Ind_2_Check_Conf ? close < jma_ma : true