// Accumulation/Distribution Money Flow (ADMF) [cI8DH]
//
// Original script: https://www.tradingview.com/script/xNwMiYef-Accumulation-Distribution-Money-Flow-Cyrus-c-D/
// Used as: Volume

acmf_len     = input(14, minval=1, title="length") // EMA27 = SMMA/RMA14 ~ lunar month
price_enable = input(true, title="factor price (=money flow)")
AD_weight    = input(0.0, minval=0.0, maxval=1.0, step=0.5, title="A/D weight (at 1 all volume is included)")

AD_ratio = nz(change(close)/tr(true)) // 'True Range' fixes issues caused by gaps in price
AD_ratio := (1 - AD_weight) * AD_ratio + sign(AD_ratio) * AD_weight

trl = min(low,close[1]), trh = max(high,close[1])
vol = price_enable ? volume * hlc3 : volume

admf = rma(vol * AD_ratio, acmf_len) 

//remove comments to use as Volume - confirmation
//Ind_3_Check_Conf = input(true, title = "Indicator 3 - Vol - Confirmation")
//Ind_3_L_Conf     = Ind_3_Check_Conf ? admf > 0 : true
//Ind_3_S_Conf     = Ind_3_Check_Conf ? admf < 0 : true