// JMA x DWMA crossover
// Original script: :shrugs:
// Used as: C1
//
// Many thanks to @BendyMan and @n0izy-cat from the Discord channel
JMAXDWMAsrc = input(title="Source", defval=close)
JMAXDWMAlength = input(title="DWMA Length", defval=10)
dwma = wma(wma(JMAXDWMAsrc, JMAXDWMAlength), JMAXDWMAlength)

// jurik
length2 = input(title="JMA Length", defval=7)
jurik(JMAXDWMAsrc, len) =>
    jurik_phase = 50
    jurik_power = 2
    phaseRatio = jurik_phase < -100 ? 0.5 : jurik_phase > 100 ? 2.5 : jurik_phase / 100 + 1.5
    beta = 0.45 * (len - 1) / (0.45 * (len - 1) + 2)
    alpha = pow(beta, jurik_power)
    jma = 0.0
    e0 = 0.0
    e0 := (1 - alpha) * JMAXDWMAsrc + alpha * nz(e0[1])
    e1 = 0.0
    e1 := (JMAXDWMAsrc - e0) * (1 - beta) + beta * nz(e1[1])
    e2 = 0.0
    e2 := (e0 + phaseRatio * e1 - nz(jma[1])) * pow(1 - alpha, 2) + pow(alpha, 2) * nz(e2[1])
    jma := e2 + nz(jma[1])
    jma

jma = jurik(JMAXDWMAsrc, length2)

//remove comments to use as C1 triggers
//Ind_1_Check_Trig = input(true, title = "Indicator 1 - C1 - Trigger")
//Ind_1_L_Trigger = Ind_1_Check_Trig ? crossover(jma, dwma)  : false
//Ind_1_S_Trigger = Ind_1_Check_Trig ? crossunder(jma, dwma) : false