// Oscar
//
// Original script: https://www.tradingview.com/script/DMmuh5v5-OSCAR-Oscillator-by-GenZai-NNFX/
// Used as: Exit or C1

len = input(title="Oscar Candles", defval=8)
slowLen = input(title="Slow Oscar Candles", defval=16)
smoothing = input(title="Oscar Smoothing", defval="RMA", options=["RMA", "SMA", "EMA", "WMA", "NONE"])
crossSignalSensitivity = input(title="Cross Signal Sensitivity", defval=0.5, step=0.1)
OscarOfIndicator = input(title="Choose input type", type=input.source, defval=close)
bottomSignalLine = input(title="Bottom Signal Line", defval=35, step=5)
topSignalLine = input(title="Top Signal Line", defval=65, step=5)

ma(smoothing, OscarParam, len) => 
    if smoothing == "RMA"
        rma(OscarParam, len)
    else
        if smoothing == "SMA"
            sma(OscarParam, len)
        else 
            if smoothing == "EMA"
                ema(OscarParam, len)
            else 
                if smoothing == "WMA"
                    wma(OscarParam, len)
                else 
                    OscarParam

A = highest(OscarOfIndicator, len)
B = lowest(OscarOfIndicator, len)
OscarRough = (OscarOfIndicator - B) / (A - B) * 100
Oscar1 = (OscarRough[1] / 3) * 2
OscarThird = OscarRough / 3
Oscar = Oscar1 + OscarThird
smoothedOscarRough = ma(smoothing, OscarRough, len)
smoothedOscar = ma(smoothing, Oscar, len)

crossSensitivity = max(smoothedOscarRough, smoothedOscar) - min(smoothedOscarRough, smoothedOscar)

//remove comments to use as C1 triggers
//Ind_1_Check_Trig = input(true, title = "Indicator 1 - C1 - Trigger")
//Ind_1_L_Trigger = Ind_1_Check_Trig ? crossover(smoothedOscarRough, smoothedOscar) and crossSensitivity > crossSignalSensitivity and smoothedOscarRough < bottomSignalLine : false
//Ind_1_S_Trigger = Ind_1_Check_Trig ? crossunder(smoothedOscarRough, smoothedOscar) and crossSensitivity > crossSignalSensitivity and smoothedOscarRough > topSignalLine : false